name: Deploy Angular & Storybook to GitHub Pages for Teenage Interface

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: |
          npm install

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli  # Installe Angular CLI globalement

      - name: Build Angular app
        run: |
          ng build --base-href /teenageinterface/

      - name: Build Storybook
        run: |
          npm run build-storybook

      - name: Deploy Angular app to GitHub Pages (docs/)
        run: |
          mkdir -p ./docs
          cp -r ./dist/teenageinterface/browser/* ./docs/
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Copy index.html to 404.html for routing fix
        run: |
          cp ./dist/teenageinterface/browser/index.html ./docs/404.html
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Deploy Storybook to GitHub Pages (docs/)
        run: |
          mkdir -p ./docs/storybook
          cp -r ./storybook-static/* ./docs/storybook
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: ./docs
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
