name: Deploy Angular & Storybook to GitHub Pages

on:
  push:
    branches:
      - main  # ou la branche de votre choix

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # utilisez la version de Node.js appropriée

      - name: Install dependencies
        run: |
          npm install

      - name: Build Angular app
        run: |
          ng build --prod

      - name: Build Storybook
        run: |
          npm run build-storybook

      - name: Deploy Angular app to GitHub Pages
        run: |
          mkdir -p ./dist/gh-pages
          cp -r ./dist/teenageinterface/* ./dist/gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Storybook to GitHub Pages
        run: |
          mkdir -p ./dist/storybook
          cp -r ./storybook-static/* ./dist/storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Pages d
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
