name: Deploy Angular & Storybook to GitHub Pages

on:
  push:
    branches:
      - main  # ou la branche de votre choix

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # utilisez la version de Node.js appropriée

      - name: Install dependencies
        run: |
          npm install

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli  # Installe Angular CLI globalement

      - name: Build Angular app
        run: |
          ng build --prod

      - name: Build Storybook
        run: |
          npm run build-storybook

      - name: Deploy Angular app to GitHub Pages (docs/)
        run: |
          mkdir -p ./docs
          cp -r ./dist/your-angular-app/* ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Storybook to GitHub Pages (docs/)
        run: |
          mkdir -p ./docs/storybook
          cp -r ./storybook-static/* ./docs/storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages  # Utilisez la branche `gh-pages` ou une autre branche
          publish_dir: ./docs        # Répertoire à publier
          github_token: ${{ secrets.GITHUB_TOKEN }}
